### ISSUE TITLE
Latest Chrome on OSX prevents video from working

### ISSUE THREAD

**Issue by vitch** [cirocosta/qcode-decoder#20]
It seems that Chrome on my laptop (Version 37.0.2062.120 on Mavericks) has stopped working with this code and all other examples I can find online. I'm not sure if this is my specific copy of Chrome / something weird on my laptop or whether this is related to a recent update.

For me it asks if I will grant access to my camera and then the video object is only 2x2px and completely dark. If I make the video bigger (with CSS) then it's still completely dark. 

The examples at https://simpl.info/ also don't work for me.

Can you reproduce or is it my specific Chrome?

**Comment by vitch** [comment]
It works on Chrome Canary on the same machine so maybe it is some sort of configuration mess on my specific Chrome?

**Comment by vitch** [comment]
And after a system restart it is all working properly again! Sorry about the noise :smile:

**Comment by cirocosta** [comment]
No problems :smile:  Maybe this can be useful for someone! :neckbeard:  Thanks!
