### ISSUE TITLE
decodeFromCamera happens only once

### ISSUE THREAD

**Issue by naglalakk** [cirocosta/qcode-decoder#29]
Hi just wondering. The once argument is described in the readme as an optional argument. However this seems to be the default behaviour for me, that QR code is only detected once and then you have to refresh. Is this expected?

**Comment by cirocosta** [comment]
Hi @enkitosh !

That makes sense. When i coded this wrapper it was targeted for an application that would need to countinuously search for qrcodes (people go to the event, get their celphones and show the qrcode that was sent to them). It made sense for that purpose. 

But as i don't have data about people's use of it i really can't tell what is the best default to be used. What do you think?

**Comment by naglalakk** [comment]
Hi @cirocosta , thank you for your answer. Funny I'm doing the exact same thing as you describe in your example. We were having this problem were we always had to refresh after each scan. Anyway it works now, I just call the function with once=false now. This library totally saved me today by the way. Excellent job :+1:
